import fs from 'node:fs/promises';
import path from 'node:path';
import { compile, CompileOptions } from 'prqlc/dist/node/prqlc_js';
import { parseCellFile, injectRefs } from '$lib/services/prql-file';
import { assertAllowedProjectFolder, assertSafe } from './project.js';

type SqlTarget = 'sql.duckdb' | 'sql.trino';

/** Parse profiles.yml and extract the adapter type for the active target. */
async function readProfileTarget(projectFolder: string): Promise<SqlTarget> {
	assertAllowedProjectFolder(projectFolder);
	try {
		const content = await fs.readFile(path.join(projectFolder, 'profiles.yml'), 'utf-8');
		const typeMatch = content.match(/^\s+type:\s*(\w+)/m);
		const type = typeMatch?.[1]?.toLowerCase();
		if (type === 'postgres' || type === 'clickhouse' || type === 'trino' || type === 'mysql') {
			return 'sql.trino';
		}
	} catch {
		// ignore — default to duckdb
	}
	return 'sql.duckdb';
}

/** Walk a directory and return all .prql file paths. */
async function findPRQLFiles(dir: string): Promise<string[]> {
	const files: string[] = [];
	async function walk(d: string): Promise<void> {
		let entries;
		try {
			entries = await fs.readdir(d, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			if (entry.isDirectory() && !entry.name.startsWith('.')) {
				await walk(path.join(d, entry.name));
			} else if (entry.isFile() && entry.name.endsWith('.prql')) {
				files.push(path.join(d, entry.name));
			}
		}
	}
	await walk(dir);
	return files;
}

/**
 * Compile a single .prql file to its companion .sql file.
 * Returns null on success or an error string on failure.
 */
export async function compileSingleModel(
	prqlPath: string,
	projectFolder: string,
	knownModels: string[]
): Promise<string | null> {
	assertAllowedProjectFolder(projectFolder);
	assertSafe(projectFolder, prqlPath);
	const target = await readProfileTarget(projectFolder);
	try {
		const content = await fs.readFile(prqlPath, 'utf-8');
		const parsed = parseCellFile(content);

		if (parsed.cellType === 'markdown') return null;
		if (!parsed.code.trim()) return null;

		let sql: string;
		try {
			const opts = new CompileOptions();
			opts.target = target;
			opts.signature_comment = false;
			const result = compile(parsed.code, opts);
			if (!result) return `${path.basename(prqlPath)}: compile returned empty`;
			sql = result;
		} catch (err) {
			return `${path.basename(prqlPath)}: ${(err as Error).message.slice(0, 200)}`;
		}

		sql = sql.replace(/\n*-- Generated by PRQL[^\n]*\n?/g, '').trim();

		const selfName = path.basename(prqlPath, '.prql');
		const otherModels = knownModels.filter((m) => m !== selfName);
		sql = injectRefs(sql, otherModels);

		const configParts: string[] = [];
		if (parsed.materializeMode && parsed.materializeMode !== 'table') {
			configParts.push(`materialized='${parsed.materializeMode}'`);
		}
		if (parsed.dbtSchema) {
			configParts.push(`schema='${parsed.dbtSchema}'`);
		}
		if (parsed.dbtTags?.length) {
			configParts.push(`tags=[${parsed.dbtTags.map((t) => `'${t}'`).join(', ')}]`);
		}

		const configBlock = configParts.length > 0 ? `{{ config(${configParts.join(', ')}) }}\n\n` : '';
		const sqlPath = prqlPath.replace(/\.prql$/, '.sql');
		assertSafe(projectFolder, sqlPath);
		await fs.writeFile(sqlPath, `${configBlock}${sql}\n`, 'utf-8');
		return null;
	} catch (err) {
		return `${path.basename(prqlPath)}: ${(err as Error).message}`;
	}
}

/**
 * Pre-compile all .prql model files to companion .sql files so dbt-fusion can
 * process them. Must be called before any `dbt compile / run / test` invocation.
 *
 * Each .prql file is:
 *   1. Parsed to extract code + dbt config metadata
 *   2. Compiled PRQL → SQL using the profile's adapter target
 *   3. Known model names are re-injected as {{ ref('name') }} Jinja calls
 *   4. A {{ config(...) }} block is prepended when non-default config is present
 *   5. Written as a .sql file next to the .prql file
 *
 * The .sql files are generated artifacts — the .prql files are the source of truth.
 */
export async function precompileProjectModels(
	projectFolder: string,
	knownModels: string[]
): Promise<{ compiled: number; errors: string[] }> {
	assertAllowedProjectFolder(projectFolder);
	const prqlFiles = [
		...(await findPRQLFiles(path.join(projectFolder, 'models'))),
		...(await findPRQLFiles(path.join(projectFolder, 'analyses')))
	];

	const results = await Promise.all(
		prqlFiles.map((prqlPath) => compileSingleModel(prqlPath, projectFolder, knownModels))
	);

	let compiled = 0;
	const errors: string[] = [];
	for (const err of results) {
		if (err) {
			errors.push(err);
		} else {
			compiled++;
		}
	}

	return { compiled, errors };
}

/** Collect all model names from .prql AND .sql files in a project.
 *  Including .sql ensures existing SQL models receive {{ ref() }} injection. */
export async function collectProjectModelNames(projectFolder: string): Promise<string[]> {
	assertAllowedProjectFolder(projectFolder);
	const names = new Set<string>();

	async function walk(dir: string): Promise<void> {
		let entries;
		try {
			entries = await fs.readdir(dir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			if (entry.isDirectory() && !entry.name.startsWith('.')) {
				await walk(path.join(dir, entry.name));
			} else if (entry.isFile()) {
				if (entry.name.endsWith('.prql') || entry.name.endsWith('.sql')) {
					names.add(entry.name.replace(/\.(prql|sql)$/, ''));
				}
			}
		}
	}

	await walk(path.join(projectFolder, 'models'));
	await walk(path.join(projectFolder, 'analyses'));
	return [...names];
}
