<script lang="ts">
	import { tick, onMount } from 'svelte';
	import { registerCellMeta, cellBridgeState } from '$lib/keyboard';
	import { findStageMenuInEditor } from '$lib/keyboard/stage-bridge';
	import { fade, fly, slide } from 'svelte/transition';
	import { Button } from '$lib/components/ui/button';
	import MarkdownEditor from './markdown/MarkdownEditor.svelte';
	import type { MarkdownEditorHandle } from './markdown/MarkdownEditor.svelte';
	import TyporaEditor from './markdown/visual/TyporaEditor.svelte';
	import * as Tooltip from '$lib/components/ui/tooltip';
	import Editor from './Editor.svelte';
	import MarkdocRenderer from './markdown/MarkdocRenderer.svelte';
	import GUIEditor from './gui/GUIEditor.svelte';
	import InlineResultView from './InlineResultView.svelte';
	import MaterializeDialog from './MaterializeDialog.svelte';
	import PromoteDialog from './PromoteDialog.svelte';
	import PromoteSeedDialog from './PromoteSeedDialog.svelte';
	import {
		prqlToGuiStages,
		extractLetBindings,
		mapErrorsToStages,
		mergeParsedWithHiddenStages
	} from '$lib/services/gui-prql';
	import { compilePRQL } from '$lib/services/prql';
	import type { PRQLStageError } from '$lib/services/gui-prql';
	import type { CompletionEntry } from '$lib/monaco/completions';
	import {
		runCell,
		cancelCell,
		runCellAndDownstream,
		updateCellCode,
		updateGuiStages,
		setEditMode,
		setCellLanguage,
		setCellDisplay,
		setStageResultCollapsed,
		registerInsertCallback,
		insertCellBefore,
		getTables,
		getExternalSchemaTables,
		runGuiStagePreview,
		getPrecedingCodeForCell,
		getConnections,
		getRunImpact,
		setCellResultViewMode,
		setCellResultChartConfig,
		updateCellColumnFormatRules,
		updateCellMarkdown,
		updateCellUdfBody,
		updatePlotCellCode,
		runPlotCell,
		updatePythonCellCode,
		runPythonCell,
		insertPythonCellAfter,
		insertCellAfter,
		getPythonAvailable,
		setCellMarkdownPreview,
		setMarkdownEditMode,
		testCell,
		getIsDbtProject,
		getProjectFolder,
		getDbtModels,
		getFocusedCellId,
		getFocusedTarget,
		clearFocusedCell,
		getCells,
		getAllCellsAcrossNotebooks,
		type CellLanguage,
		type Cell,
		getCrossNotebookUsageCount,
		getSameNotebookUsageCount,
		openWorksheetView
	} from '$lib/stores/notebook.svelte';
	import InlinePromptBar from './cell/InlinePromptBar.svelte';
	import { isChipEditing } from '$lib/stores/chip-edit.svelte';
	import { updateProjectSchema } from '$lib/services/project-client';
	import { resolvePlotDataRefs } from '$lib/services/cell-deps';
	import { buildSandboxGlobalsDts } from '$lib/services/plot-cell';
	import { PLOT_TEMPLATES } from '$lib/services/plot-templates';
	import PlotCellOutput from './PlotCellOutput.svelte';
	import PythonCellOutput from './PythonCellOutput.svelte';

	import type { GUIPipelineStage, GUISourceSchema } from '$lib/types/gui-pipeline';
	import type { ResultViewMode } from '$lib/types/gui-pipeline';
	import { Loader2, ExternalLink, GripVertical } from '@lucide/svelte';
	import CellGutter from './cell/CellGutter.svelte';
	import CellHeader from './cell/CellHeader.svelte';
	import CellMenu from './cell/CellMenu.svelte';
	import {
		getCellCommentCount,
		openCommentPanel,
		refreshCellCount,
		sendPresence
	} from '$lib/stores/comments.svelte';
	import { getReviewMode } from '$lib/stores/comments.svelte';
	import CellStatusLine from './cell/CellStatusLine.svelte';
	import CellSqlPreview from './cell/CellSqlPreview.svelte';
	import CellModeSwitchDialogs from './cell/CellModeSwitchDialogs.svelte';
	import {
		BUILTIN_DUCKDB_CONNECTION_ID,
		getPRQLTargetForConnection,
		resolveConnection
	} from '$lib/types/connection';
	import { renderMarkdocCell, extractMarkdocRefs } from '$lib/services/markdoc-interp';
	import { markdocPmRoundTripLossy } from '$lib/services/markdoc-pm';
	import { shouldHideCellInReportView } from '$lib/services/filter-frozen';
	import MarkdownToolbar from './markdown/MarkdownToolbar.svelte';
	import MarkdownModeBar from './markdown/MarkdownModeBar.svelte';
	import type { FormatAction } from './markdown/MarkdownToolbar.svelte';

	interface Props {
		cell: Cell;
		index: number;
		isFirst: boolean;
		isLast: boolean;
		dark?: boolean;
		prevCellSources?: GUISourceSchema[];
		notebookId?: string;
		autoRun?: boolean;
		/** Presentation mode: render as output-only with cell chrome hidden. */
		reportView?: boolean;
		/** Cell is currently being generated by AI — shows ghost styling. */
		isGhost?: boolean;
		/** Called when the user clicks "Share with AI" in the cell header. */
		onShareWithAI?: () => void;
		/** Called when the user clicks "Fix with AI" in the error popover. */
		onFixWithAI?: (errorMsg: string) => void;
		/** Called from the inline AI prompt's "Continue in AI chat" link. */
		onContinueWithAI?: (instruction: string) => void;
		onOpenResultTab?: (
			cellId: string,
			notebookId: string,
			name: string,
			preferredViewMode?: ResultViewMode
		) => void;
		collabEnabled?: boolean;
		/** Worksheet (maximized) view — fills parent with resizable editor/result split */
		worksheet?: boolean;
	}

	let {
		cell,
		index,
		isFirst,
		isLast,
		dark = false,
		prevCellSources = [],
		notebookId = '',
		autoRun = false,
		reportView = false,
		isGhost = false,
		onShareWithAI,
		onFixWithAI,
		onContinueWithAI,
		onOpenResultTab,
		collabEnabled = false,
		worksheet = false
	}: Props = $props();

	const reviewMode = $derived(getReviewMode());
	const commentCount = $derived(getCellCommentCount(cell.id));
	const hasOpenComments = $derived(commentCount > 0);

	$effect(() => {
		if (collabEnabled && notebookId && cellFocused) {
			void sendPresence(notebookId, cell.id);
		}
	});

	function openCellComments(): void {
		if (!notebookId) return;
		openCommentPanel({ notebookId, cellId: cell.id });
	}

	let editorRef: Editor | undefined = $state();
	let inlinePromptOpen = $state(false);
	let inlinePromptPreset = $state<string | null>(null);
	let sqlExpanded = $state(false);
	let entering = $state(true);
	onMount(() => {
		if (collabEnabled) void refreshCellCount(cell.id);
		setTimeout(() => (entering = false), 220);
	});
	let autoRunTimer: ReturnType<typeof setTimeout> | undefined;
	let pendingAutoRun = $state(false);
	let menuOpen = $state(false);
	let materializeDialogOpen = $state(false);
	let promoteDialogOpen = $state(false);
	let promoteSeedDialogOpen = $state(false);
	// Portaled popovers (status chips, refs, errors) take focus outside the cell
	// element; keep the cell chrome revealed while any of them is open.
	let overlayCount = $state(0);
	function handleOverlayChange(open: boolean) {
		overlayCount = Math.max(0, overlayCount + (open ? 1 : -1));
	}

	// "Fix with AI" from the error popover — prefer the fast inline path when this cell
	// supports it; otherwise fall back to whatever the parent wired up (sidebar chat).
	function handleFixWithAI(errorMsg: string) {
		if (canInlinePrompt) {
			// Prefer the structured error (display/hint) over the flattened string the
			// popover passes — gives the agent more to work with than a bare message.
			const err = cell.errors[0];
			inlinePromptPreset = err
				? [
						`Fix this error: ${err.display ?? err.reason ?? errorMsg}`,
						err.hint ? `Hint: ${err.hint}` : null
					]
						.filter(Boolean)
						.join('\n')
				: `Fix this error: ${errorMsg}`;
			inlinePromptOpen = true;
			return;
		}
		onFixWithAI?.(errorMsg);
	}

	// Inline AI prompt applied the suggested alternative cell type — insert a new cell
	// right after this one rather than mutating it (the original stays untouched).
	function handleCreateAlternative(alt: {
		cellType: 'query' | 'python';
		language?: 'sql' | 'prql';
		code: string;
	}) {
		if (alt.cellType === 'python') {
			const newId = insertPythonCellAfter(cell.id);
			if (newId) updatePythonCellCode(newId, alt.code);
			return;
		}
		insertCellAfter(cell.id, {
			outputName: '',
			code: alt.code,
			guiStages: [{ type: 'from', table: '' }],
			editMode: 'prql',
			language: alt.language ?? 'sql'
		});
	}
	const EDITOR_COMPLETION_LIMIT = 600;
	const PRQL_KEYWORDS = [
		'from',
		'select',
		'derive',
		'filter',
		'group',
		'aggregate',
		'sort',
		'take',
		'join',
		'let',
		'case'
	] as const;
	const isQueryCell = $derived(cell.cellType === 'query');
	const isUdfCell = $derived(cell.cellType === 'udf');
	const isMarkdownCell = $derived(cell.cellType === 'markdown');
	const isPlotCell = $derived(cell.cellType === 'plot');
	const isPythonCell = $derived(cell.cellType === 'python');
	// Raw-code editor cells the inline "Tell AI what to do" prompt supports — GUI-mode
	// query cells have their own AI entry via AddStageMenu instead.
	const canInlinePrompt = $derived((isQueryCell && cell.editMode !== 'gui') || isPythonCell);
	const plotDeps = $derived(
		isPlotCell
			? resolvePlotDataRefs(
					getCells(),
					getCells().findIndex((c) => c.id === cell.id)
				)
			: []
	);
	const plotCellGlobalsDts = $derived(buildSandboxGlobalsDts(plotDeps));
	// Report view renders query cells as output-only, unless they are explicitly
	// collapsed — collapsed cells are hidden entirely in report mode.
	const effectiveDisplay = $derived(
		worksheet
			? 'full'
			: reportView && isQueryCell && cell.display !== 'collapsed'
				? 'output'
				: cell.display
	);
	const collapsed = $derived(!worksheet && effectiveDisplay === 'collapsed');
	const hiddenInReportView = $derived(
		!worksheet && reportView && shouldHideCellInReportView(cell, getCells())
	);
	const codeHidden = $derived(!worksheet && isQueryCell && effectiveDisplay !== 'full');
	const markdownEditorHidden = $derived(
		!worksheet && isMarkdownCell && effectiveDisplay !== 'full'
	);
	const headerCodeHidden = $derived(isMarkdownCell ? markdownEditorHidden : codeHidden);
	const supportsWorksheet = $derived(isQueryCell || isPythonCell || isPlotCell);
	const editorLayout = $derived(worksheet ? ('fill' as const) : ('auto' as const));

	function handleOpenWorksheet() {
		if (notebookId) openWorksheetView(notebookId, cell.id);
	}

	const MIN_WORKSHEET_EDITOR_HEIGHT = 160;
	let worksheetBodyEl: HTMLElement | undefined = $state();
	let editorHeight = $state(320);
	let splitResizing = $state(false);
	let splitResizeStartY = 0;
	let splitResizeStartHeight = 0;

	function onSplitResizeStart(e: PointerEvent) {
		splitResizing = true;
		splitResizeStartY = e.clientY;
		splitResizeStartHeight = editorHeight;
		(e.target as HTMLElement).setPointerCapture(e.pointerId);
	}
	function onSplitResizeMove(e: PointerEvent) {
		if (!splitResizing) return;
		editorHeight = Math.max(
			MIN_WORKSHEET_EDITOR_HEIGHT,
			splitResizeStartHeight + (e.clientY - splitResizeStartY)
		);
	}
	function onSplitResizeEnd() {
		splitResizing = false;
	}

	$effect(() => {
		if (!worksheet || !worksheetBodyEl) return;
		const ro = new ResizeObserver(() => {
			if (editorHeight === 320 && worksheetBodyEl) {
				editorHeight = Math.max(
					MIN_WORKSHEET_EDITOR_HEIGHT,
					Math.round(worksheetBodyEl.clientHeight * 0.45)
				);
			}
		});
		ro.observe(worksheetBodyEl);
		return () => ro.disconnect();
	});
	let running = $derived(cell.status === 'running');
	let cellFocused = $state(false);
	let cellHovered = $state(false);
	let cellContainerEl: HTMLElement | undefined = $state();

	$effect(() => {
		const target = getFocusedTarget();
		if (target?.cellId !== cell.id || !cellContainerEl) return;
		void (async () => {
			cellContainerEl!.scrollIntoView({ behavior: 'smooth', block: 'start' });
			if (target.anchorId) {
				await tick();
				const anchor = cellContainerEl!.querySelector<HTMLElement>(
					`#${CSS.escape(target.anchorId)}`
				);
				anchor?.scrollIntoView({ behavior: 'smooth', block: 'start' });
			}
			clearFocusedCell();
		})();
	});

	let confirmSwitchToGui = $state(false);
	let confirmSwitchToSql = $state<false | 'with-code' | 'without-code'>(false);
	let compiledSqlForSwitch = $state('');
	let confirmSwitchToPrql = $state(false);
	let confirmSwitchToVisualMarkdown = $state(false);
	let markdownEditContainerEl: HTMLDivElement | null = $state(null);
	let markdownHandle: MarkdownEditorHandle | null = $state(null);
	const revealed = $derived(
		worksheet || (!reportView && (cellFocused || cellHovered || menuOpen || overlayCount > 0))
	);
	const showCellIndex = $derived(
		!worksheet &&
			(isQueryCell || isPythonCell) &&
			(revealed || running || cell.needsRun || cell.status === 'error')
	);
	const showResultControls = $derived(worksheet || revealed);
	const showResult = $derived(
		!collapsed &&
			!cell.hideResult &&
			Boolean(cell.result) &&
			(cell.status === 'success' || cell.status === 'running')
	);
	const showPythonOutput = $derived(
		!collapsed && !cell.hideResult && isPythonCell && cell.pythonOutput
	);
	const markdocResult = $derived.by(() => {
		if (!isMarkdownCell || !cell.markdown?.trim()) return null;
		return renderMarkdocCell(cell.markdown ?? '', getAllCellsAcrossNotebooks());
	});
	const isMarkdownPreviewMode = $derived(
		isMarkdownCell &&
			(cell.markdownPreview || markdownEditorHidden || reportView) &&
			!!cell.markdown?.trim()
	);
	const isMarkdownOutputOnly = $derived(
		isMarkdownCell && (reportView || markdownEditorHidden) && !!cell.markdown?.trim()
	);
	const isMarkdownVisualEditing = $derived(
		isMarkdownCell && cell.markdownEditMode === 'visual' && !isMarkdownOutputOnly
	);
	const isMarkdownSourceEditing = $derived(
		isMarkdownCell && cell.markdownEditMode === 'source' && !isMarkdownOutputOnly
	);
	const isMarkdownRendered = $derived(isMarkdownOutputOnly);
	const isMarkdownClickToEdit = $derived(false);
	const markdownMode = $derived<'visual' | 'source'>(
		cell.markdownEditMode === 'source' ? 'source' : 'visual'
	);

	const MARKDOWN_INTERACTIVE_SELECTOR =
		'a, button, input, select, textarea, label, [role="tab"], [role="tablist"], .md-filter, .md-details';
	const hasLiveRefs = $derived(
		isMarkdownCell && extractMarkdocRefs(cell.markdown ?? '').length > 0
	);
	const refPickerEntries = $derived(
		getAllCellsAcrossNotebooks()
			.filter((c) => c.cellType === 'query' && c.result)
			.map((c) => ({ cellName: c.outputName, columns: c.result!.columns }))
	);
	const markdownRefEntries = $derived(
		refPickerEntries.map((e) => ({
			cellName: e.cellName,
			columns: e.columns.map((name) => ({ name }))
		}))
	);
	const markdownValidationCells = $derived(getAllCellsAcrossNotebooks());

	function insertMarkdownSnippet(snippet: string) {
		markdownHandle?.insertText(snippet);
	}

	function insertMarkdownRef(cellName: string, column: string) {
		insertMarkdownSnippet(`$${cellName}.${column}`);
	}

	function handleMarkdownPreviewClick(e: MouseEvent) {
		if ((e.target as HTMLElement).closest(MARKDOWN_INTERACTIVE_SELECTOR)) return;
		setCellDisplay(cell.id, 'full');
	}

	function requestVisualMarkdownMode() {
		if (!isMarkdownCell) return;
		const md = cell.markdown ?? '';
		const { lossy } = markdocPmRoundTripLossy(md);
		if (!lossy || !md.trim()) {
			setMarkdownEditMode(cell.id, 'visual');
			return;
		}
		confirmSwitchToVisualMarkdown = true;
	}

	function setMarkdownMode(mode: 'visual' | 'source') {
		if (!isMarkdownCell) return;
		if (effectiveDisplay !== 'full') setCellDisplay(cell.id, 'full');
		if (cell.markdownPreview) setCellMarkdownPreview(cell.id, false);
		if (mode === 'visual') {
			requestVisualMarkdownMode();
			return;
		}
		setMarkdownEditMode(cell.id, 'source');
	}

	function setMarkdownPreviewMode(preview: boolean) {
		if (!isMarkdownCell) return;
		if (preview) {
			setCellDisplay(cell.id, 'output');
			return;
		}
		setCellDisplay(cell.id, 'full');
	}

	function doSwitchToVisualMarkdown() {
		confirmSwitchToVisualMarkdown = false;
		setMarkdownEditMode(cell.id, 'visual');
	}

	const prevCellNames = $derived(prevCellSources.map((source) => source.name));
	const tables = $derived(getTables());
	const externalSchemaTables = $derived(getExternalSchemaTables());
	const connections = $derived(getConnections());
	const connectionValue = $derived(cell.connectionId ?? BUILTIN_DUCKDB_CONNECTION_ID);

	// Coarse "what tables exist" context for the inline AI prompt — not pipeline-resolved
	// like guiTables below, just enough so the model doesn't invent table/column names.
	const inlinePromptTables = $derived(
		[...tables, ...externalSchemaTables]
			.slice(0, 8)
			.map((t) => ({ name: t.name, columns: t.columns, columnTypes: t.columnTypes }))
	);

	function sqlTypeToDataKind(sqlType: string): 'numeric' | 'date' | 'boolean' | 'text' {
		const t = sqlType.toUpperCase();
		if (/INT|DECIMAL|NUMERIC|DOUBLE|FLOAT|REAL/.test(t)) return 'numeric';
		if (/DATE|TIME/.test(t)) return 'date';
		if (/BOOL/.test(t)) return 'boolean';
		return 'text';
	}

	// Best-effort "main table" for this cell's inline AI prompt, parsed from its own FROM
	// clause — raw text cells have no GUI "from" stage to read this from directly. Lets
	// rankColumnsByRelevance/buildSchemaBlock (ai-schema-context.ts) actually engage instead
	// of always falling back to the bare "available tables" list.
	const inlinePromptSourceTable = $derived.by(() => {
		if (!isQueryCell) return undefined;
		const fromRe =
			cell.language === 'sql' ? /\bFROM\s+([a-zA-Z_][\w."]*)/i : /^\s*from\s+([a-zA-Z_][\w.]*)/im;
		const match = cell.code.match(fromRe);
		if (!match) return undefined;
		const candidate = match[1].replace(/"/g, '');
		const found = [...tables, ...externalSchemaTables].find(
			(t) => t.name.toLowerCase() === candidate.toLowerCase()
		);
		return found?.name;
	});

	const inlinePromptColumns = $derived.by(() => {
		const name = inlinePromptSourceTable;
		if (!name) return [];
		const found = [...tables, ...externalSchemaTables].find((t) => t.name === name);
		if (!found) return [];
		return found.columns.map((col, i) => ({
			name: col,
			dataKind: sqlTypeToDataKind(found.columnTypes[i] ?? ''),
			sqlType: found.columnTypes[i]
		}));
	});

	const connectionType = $derived.by(() => {
		const connection = connections.find((entry) => entry.id === connectionValue);
		return connection?.type ?? 'duckdb-wasm';
	});

	const cellExternalSchema = $derived(
		externalSchemaTables.filter((t) => t.connectionId === connectionValue)
	);

	// For Trino-backed sources, produce 3-part names (catalogName.schema.table) in completions
	const cellCatalogName = $derived.by(() => {
		if (connectionType === 'duckdb-wasm') return undefined;
		const conn = connections.find((c) => c.id === connectionValue);
		return (conn as { catalogName?: string } | undefined)?.catalogName;
	});

	const guiTables = $derived.by(() => {
		if (connectionValue === BUILTIN_DUCKDB_CONNECTION_ID) {
			return tables;
		}
		const merged: typeof tables = [];
		const seen = new Set<string>();
		for (const table of externalSchemaTables) {
			if (table.connectionId !== connectionValue) continue;
			const qualifiedName =
				cellCatalogName && table.schema
					? `${cellCatalogName}.${table.schema}.${table.name}`
					: table.schema
						? `${table.schema}.${table.name}`
						: table.name;
			if (seen.has(qualifiedName)) continue;
			seen.add(qualifiedName);
			merged.push({
				name: qualifiedName,
				fileName: qualifiedName,
				rowCount: 0,
				columns: table.columns,
				columnTypes: table.columnTypes
			});
		}
		return merged;
	});
	const cellSqlDialect = $derived(
		getPRQLTargetForConnection(resolveConnection(connections, cell.connectionId))
	);
	const isDbtProject = $derived(getIsDbtProject());
	const projectFolder = $derived(getProjectFolder());

	// Column descriptions from the matching dbt model (keyed by column name)
	const columnDescriptions = $derived.by((): Record<string, string> => {
		if (!isDbtProject) return {};
		const model = getDbtModels().find((m) => m.name === cell.outputName);
		if (!model) return {};
		return Object.fromEntries(
			model.columns.filter((c) => c.description).map((c) => [c.name, c.description!])
		);
	});

	function handleColumnDescriptionChange(column: string, description: string) {
		if (!projectFolder || !notebookId) return;
		const relPath = `${notebookId}.prql`;
		updateProjectSchema(projectFolder, relPath, {
			columns: [{ name: column, description }]
		}).catch(() => {});
		// Optimistically update dbt model in store
		const models = getDbtModels();
		const model = models.find((m) => m.name === cell.outputName);
		if (model) {
			const col = model.columns.find((c) => c.name === column);
			if (col) col.description = description;
			else model.columns.push({ name: column, dataType: 'unknown', description, tests: [] });
		}
	}

	const schemaMetaByTable = $derived.by(() => {
		const map = new Map<string, { description?: string; columnDescriptions?: string[] }>();
		for (const table of externalSchemaTables) {
			if (table.connectionId !== connectionValue) continue;
			const qualifiedName =
				cellCatalogName && table.schema
					? `${cellCatalogName}.${table.schema}.${table.name}`
					: table.schema
						? `${table.schema}.${table.name}`
						: table.name;
			map.set(qualifiedName, {
				description: table.description,
				columnDescriptions: table.columnDescriptions
			});
		}
		return map;
	});

	const editorCompletions = $derived.by((): CompletionEntry[] => {
		if (!isQueryCell || collapsed || codeHidden) return [];
		if (cell.language !== 'sql' && cell.editMode !== 'prql') return [];

		type EntryMeta = { detail?: string; description?: string };
		const entries = new Map<string, EntryMeta>();
		const setEntry = (text: string, detail?: string, description?: string) => {
			if (!text) return;
			const prev = entries.get(text);
			entries.set(text, {
				detail: detail ?? prev?.detail,
				description: description ?? prev?.description
			});
		};

		if (cell.language !== 'sql') {
			for (const kw of PRQL_KEYWORDS) setEntry(kw);
		}

		for (const table of guiTables) {
			if (entries.size >= EDITOR_COMPLETION_LIMIT) break;
			const meta = schemaMetaByTable.get(table.name);
			const parts = table.name.split('.');
			setEntry(table.name, undefined, meta?.description);
			// Also register without catalog prefix so `schema.table` in SQL matches registry.
			if (parts.length === 3) {
				const shortName = `${parts[1]}.${parts[2]}`;
				setEntry(shortName, undefined, meta?.description);
			}
			for (let i = 0; i < table.columns.length; i++) {
				if (entries.size >= EDITOR_COMPLETION_LIMIT) break;
				const col = table.columns[i];
				setEntry(`${table.name}.${col}`, table.columnTypes?.[i], meta?.columnDescriptions?.[i]);
				if (parts.length === 3) {
					setEntry(
						`${parts[1]}.${parts[2]}.${col}`,
						table.columnTypes?.[i],
						meta?.columnDescriptions?.[i]
					);
				}
			}
		}

		for (const source of prevCellSources) {
			if (entries.size >= EDITOR_COMPLETION_LIMIT) break;
			setEntry(source.name);
			for (const column of source.columns) {
				if (entries.size >= EDITOR_COMPLETION_LIMIT) break;
				if (cell.language === 'sql') {
					setEntry(`${source.name}.${column}`);
				} else {
					setEntry(column);
				}
			}
		}

		if (cell.language === 'sql') {
			for (const c of getAllCellsAcrossNotebooks()) {
				if (entries.size >= EDITOR_COMPLETION_LIMIT) break;
				if (c.cellType === 'udf' && c.outputName) setEntry(c.outputName);
			}
		}

		return Array.from(entries, ([text, meta]) => ({
			text,
			detail: meta.detail,
			description: meta.description
		}));
	});

	// Names of UDF cells visible to this cell, told to the SQL formatter so it
	// doesn't add a space before their call parens (see Editor.svelte).
	const udfFunctionNames = $derived.by((): string[] => {
		if (cell.language !== 'sql') return [];
		const names: string[] = [];
		for (const c of getAllCellsAcrossNotebooks()) {
			if (c.cellType === 'udf' && c.outputName) names.push(c.outputName);
		}
		return names;
	});
	const runImpact = $derived(getRunImpact(cell.id));
	const runTooltipText = $derived.by(() => {
		if (!isQueryCell) return '';
		if (runImpact.segmentCount <= 1) return 'Run cell (⇧↵ or ⌘↵)';
		return `Run cell (⇧↵ or ⌘↵). Also reruns ${runImpact.downstreamCount} downstream cell${runImpact.downstreamCount === 1 ? '' : 's'}.`;
	});
	const intelligenceSummary = $derived.by(() => {
		if (!cell.intelligence) return null;
		const qualityWarnings = cell.intelligence.dataQuality.filter(
			(check) => check.status === 'warn'
		).length;
		const perfWarnings = cell.intelligence.performance.filter(
			(item) => item.severity === 'warn'
		).length;
		return {
			rowCount: cell.intelligence.rowCount,
			columnCount: cell.intelligence.columnCount,
			connectionId: cell.intelligence.connectionId,
			nextAnalysis: cell.intelligence.nextAnalyses[0] ?? null,
			qualityWarnings,
			perfWarnings,
			joinCount: cell.intelligence.joinSuggestions.length,
			schemaMatchCount: cell.intelligence.semanticMatches.length
		};
	});

	// Map cell compile errors to specific GUI pipeline stages
	const stageErrorMap = $derived(
		cell.editMode === 'gui' && cell.errors.length > 0
			? mapErrorsToStages(
					cell.guiStages,
					cell.errors,
					(() => {
						const p = getPrecedingCodeForCell(cell.id);
						return p ? p.split('\n').length : 0;
					})()
				)
			: new Map<number, PRQLStageError[]>()
	);

	// Auto-run: re-run this cell (and its downstream segment) after content changes
	$effect(() => {
		if (!isQueryCell) return;
		// Track content — code in PRQL mode, stages in GUI mode
		const _content = cell.editMode === 'gui' ? JSON.stringify(cell.guiStages) : cell.code;

		clearTimeout(autoRunTimer);

		if (!autoRun) return;

		autoRunTimer = setTimeout(() => {
			if (cell.status === 'running' || isChipEditing()) {
				pendingAutoRun = true;
			} else {
				runCellAndDownstream(cell.id);
			}
		}, 1500);

		return () => clearTimeout(autoRunTimer);
	});

	// Deferred rerun: if a run completed (or chip editing ended) while
	// pendingAutoRun was set, run now
	$effect(() => {
		if (cell.status !== 'running' && !isChipEditing() && pendingAutoRun) {
			pendingAutoRun = false;
			runCellAndDownstream(cell.id);
		}
	});

	function requestGuiMode() {
		if (cell.editMode !== 'prql') {
			setEditMode(cell.id, 'gui');
			return;
		}

		const trimmed = cell.code.trim();
		if (!trimmed) {
			setEditMode(cell.id, 'gui');
			return;
		}

		// If the PRQL has `let` bindings, split into separate cells
		const { letBindings, mainPrql } = extractLetBindings(cell.code);
		if (letBindings.length > 0) {
			for (const binding of letBindings) {
				const innerStages = prqlToGuiStages(binding.rawCode);
				insertCellBefore(cell.id, {
					outputName: binding.name,
					code: binding.rawCode,
					guiStages: innerStages ?? [{ type: 'from', table: '' }],
					editMode: innerStages ? 'gui' : 'prql'
				});
			}
			const mainStages = prqlToGuiStages(mainPrql);
			if (mainStages) {
				updateGuiStages(cell.id, mergeParsedWithHiddenStages(cell.guiStages, mainStages));
				setEditMode(cell.id, 'gui');
			} else {
				updateCellCode(cell.id, mainPrql);
				// keep prql mode — main pipeline couldn't be parsed
			}
			return;
		}

		const parsedStages = prqlToGuiStages(cell.code);
		if (parsedStages) {
			updateGuiStages(cell.id, mergeParsedWithHiddenStages(cell.guiStages, parsedStages));
			setEditMode(cell.id, 'gui');
			return;
		}

		confirmSwitchToGui = true;
	}

	function doSwitchToGui() {
		confirmSwitchToGui = false;
		// Reset stages to a blank pipeline and switch mode
		updateGuiStages(cell.id, [{ type: 'from', table: '' }]);
		setEditMode(cell.id, 'gui');
	}

	function switchToPrqlMode() {
		if (!isQueryCell) return;
		setEditMode(cell.id, 'prql');
	}

	function onCellFocusIn() {
		cellFocused = true;
	}

	function onCellFocusOut(e: FocusEvent) {
		const el = e.currentTarget as HTMLElement;
		if (!el.contains(e.relatedTarget as Node)) {
			cellFocused = false;
		}
	}

	function onEditorFocus() {
		if (!isQueryCell) return;
		registerInsertCallback((text) => editorRef?.insertAtCursor(text));
	}

	function enterEditMode() {
		if (isUdfCell || (isQueryCell && cell.editMode === 'prql')) {
			editorRef?.focus();
		} else if (isQueryCell && cell.editMode === 'gui') {
			cellContainerEl?.querySelector<HTMLElement>('.stage-card[tabindex]')?.focus();
		} else if (!reportView) {
			markdownHandle?.focus();
		}
	}

	// Click-outside-to-preview: fires when user clicks outside the edit container.
	// Monaco's suggest/find widgets are fixedOverflowWidgets rendered outside the container —
	// guard against those too so clicking a completion doesn't dismiss edit mode.
	$effect(() => {
		if (isMarkdownPreviewMode || reportView || !markdownEditContainerEl) return;
		function handleMousedown(e: MouseEvent) {
			if (markdownEditContainerEl?.contains(e.target as Node)) return;
			if (
				(e.target as HTMLElement)?.closest(
					'.monaco-editor, .suggest-widget, .parameter-hints-widget, .context-view, .shadow-root-host'
				)
			)
				return;
			if (cell.markdown?.trim()) setCellMarkdownPreview(cell.id, true);
		}
		document.addEventListener('mousedown', handleMousedown);
		return () => document.removeEventListener('mousedown', handleMousedown);
	});

	$effect(() => {
		return registerCellMeta({
			cellId: cell.id,
			canInlinePrompt: canInlinePrompt,
			isQueryCell,
			isGuiCell: isQueryCell && cell.editMode === 'gui',
			isDbtProject: getIsDbtProject(),
			worksheetEligible: supportsWorksheet,
			collapsed,
			display: effectiveDisplay,
			outputName: cell.outputName ?? ''
		});
	});

	$effect(() => {
		if (cellBridgeState.pendingInlinePromptCellId === cell.id) {
			cellBridgeState.pendingInlinePromptCellId = null;
			inlinePromptOpen = true;
		}
	});

	$effect(() => {
		if (cellBridgeState.pendingEnterEditCellId === cell.id) {
			cellBridgeState.pendingEnterEditCellId = null;
			enterEditMode();
		}
	});

	$effect(() => {
		if (cellBridgeState.pendingGuiSlashCellId !== cell.id) return;
		cellBridgeState.pendingGuiSlashCellId = null;
		if (!isQueryCell || cell.editMode !== 'gui') return;
		enterEditMode();
		void tick().then(() => {
			const editor = cellContainerEl?.querySelector<HTMLElement>('.stage-editor');
			if (!editor) return;
			findStageMenuInEditor(editor)?.openMenu();
		});
	});

	function handleToolbarFormat(action: FormatAction) {
		markdownHandle?.format(action);
	}

	function addSortSuggestion(column: string, dir: 'asc' | 'desc') {
		if (cell.editMode !== 'gui') return;
		updateGuiStages(cell.id, [...cell.guiStages, { type: 'sort', keys: [{ column, dir }] }]);
	}

	function addFilterSuggestion(column: string) {
		if (cell.editMode !== 'gui') return;
		updateGuiStages(cell.id, [
			...cell.guiStages,
			{ type: 'filter', conditions: [{ column, op: '==', value: '' }], logic: 'and' }
		]);
	}

	const crossNotebookUsageCount = $derived(
		isQueryCell && cell.outputName && notebookId
			? getCrossNotebookUsageCount(cell.outputName, notebookId)
			: 0
	);
	const sameNotebookUsageCount = $derived(
		isQueryCell && cell.outputName && notebookId
			? getSameNotebookUsageCount(cell.outputName, notebookId, cell.id)
			: 0
	);

	// Combined cell mode: collapses language + editMode into a single concept
	const cellMode = $derived<'prql' | 'visual' | 'sql'>(
		cell.language === 'sql' ? 'sql' : cell.editMode === 'gui' ? 'visual' : 'prql'
	);

	function setCellMode(mode: 'prql' | 'visual' | 'sql') {
		if (mode === 'sql') {
			if (cell.editMode === 'gui') switchToPrqlMode();
			if (cell.language !== 'sql' && cell.code.trim()) {
				const result = compilePRQL(cell.code, cellSqlDialect);
				if (result.errors.length === 0 && result.sql) {
					compiledSqlForSwitch = result.sql;
					confirmSwitchToSql = 'with-code';
				} else {
					confirmSwitchToSql = 'without-code';
				}
			} else {
				setCellLanguage(cell.id, 'sql');
			}
		} else if (mode === 'prql') {
			if (cell.editMode === 'gui') switchToPrqlMode();
			if (cell.language === 'sql' && cell.code.trim()) {
				confirmSwitchToPrql = true;
			} else {
				setCellLanguage(cell.id, 'prql');
			}
		} else {
			if (cell.language === 'sql') setCellLanguage(cell.id, 'prql');
			requestGuiMode();
		}
	}

	function doSwitchToSql(useCompiledCode: boolean) {
		confirmSwitchToSql = false;
		setCellLanguage(cell.id, 'sql');
		if (useCompiledCode && compiledSqlForSwitch) {
			updateCellCode(cell.id, compiledSqlForSwitch);
		}
		compiledSqlForSwitch = '';
	}

	function doSwitchToPrql() {
		confirmSwitchToPrql = false;
		setCellLanguage(cell.id, 'prql');
	}

	// Connection name shown in the status line — only for non-default connections
	const cellConnectionName = $derived(
		cell.connectionId ? (connections.find((c) => c.id === cell.connectionId)?.name ?? null) : null
	);

	const hasStatusLine = $derived(
		!worksheet &&
			(isQueryCell || isPythonCell) &&
			!collapsed &&
			!reportView &&
			(showResult ||
				(cell.needsRun && cell.status !== 'running') ||
				cell.materializeStatus !== 'idle' ||
				cell.scheduleEnabled ||
				(isDbtProject && cell.dbtTestStatus !== 'idle') ||
				cellConnectionName !== null)
	);
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions a11y_no_noninteractive_tabindex -->
<div
	bind:this={cellContainerEl}
	class="notebook-cell group relative text-foreground outline-none {worksheet
		? 'flex min-h-0 flex-1 flex-col p-0'
		: 'py-[var(--notebook-cell-gap)]'} {entering ? 'is-entering' : ''} {worksheet || reportView
		? ''
		: running
			? ''
			: ''} {isGhost ? 'rounded-md ring-1 ring-primary/25' : ''}"
	hidden={hiddenInReportView}
	data-focused={cellFocused}
	data-cell-id={cell.id}
	data-cell-type={cell.cellType}
	data-worksheet={worksheet ? true : undefined}
	tabindex="0"
	onfocusin={onCellFocusIn}
	onfocusout={onCellFocusOut}
	onmouseenter={() => (cellHovered = true)}
	onmouseleave={() => (cellHovered = false)}
	role="region"
	aria-label={`Cell ${index + 1}`}
	aria-busy={running}
>
	{#snippet editorInner()}
		{#if canInlinePrompt}
			<InlinePromptBar
				bind:open={inlinePromptOpen}
				cellId={cell.id}
				cellType={isPythonCell ? 'python' : 'query'}
				language={isPythonCell ? undefined : cell.language}
				code={cell.code}
				outputName={cell.outputName}
				pythonAvailable={getPythonAvailable()}
				sourceTable={inlinePromptSourceTable}
				columns={inlinePromptColumns}
				otherTables={inlinePromptTables}
				{editorRef}
				autoSubmitInstruction={inlinePromptPreset}
				onAutoSubmitConsumed={() => (inlinePromptPreset = null)}
				onApply={(code) =>
					isPythonCell ? updatePythonCellCode(cell.id, code) : updateCellCode(cell.id, code)}
				onCreateAlternative={handleCreateAlternative}
				onContinueInChat={onContinueWithAI}
			/>
		{/if}
		{#if isUdfCell}
			<div class="notebook-code-block">
				<Editor
					bind:this={editorRef}
					code={cell.udfBody}
					errors={cell.errors}
					language="python"
					pythonContext={{ kind: 'udf' }}
					{dark}
					layout={editorLayout}
					embeddedNotebook
					onchange={(c) => updateCellUdfBody(cell.id, c)}
				/>
			</div>
		{:else if isPlotCell}
			<div class="mb-1 flex justify-end">
				<select
					class="h-6 rounded-md border border-input bg-background px-1.5 text-2xs text-muted-foreground"
					value=""
					onchange={(e) => {
						const select = e.target as HTMLSelectElement;
						const tpl = PLOT_TEMPLATES.find((t) => t.id === select.value);
						if (tpl) editorRef?.insertAtCursor(tpl.code);
						select.value = '';
					}}
				>
					<option value="" disabled selected>Insert template…</option>
					{#each PLOT_TEMPLATES as tpl (tpl.id)}
						<option value={tpl.id}>{tpl.label}</option>
					{/each}
				</select>
			</div>
			<div class="notebook-code-block">
				<Editor
					bind:this={editorRef}
					code={cell.code}
					errors={cell.errors}
					language="javascript"
					plotGlobalsDts={plotCellGlobalsDts}
					{dark}
					layout={editorLayout}
					embeddedNotebook
					onchange={(c) => updatePlotCellCode(cell.id, c)}
				/>
			</div>
			{#if !worksheet}
				<p class="mt-1 text-2xs text-muted-foreground">
					Reference upstream cells by name (e.g. <code>my_query.rows</code>) and
					<code>return {'{ data: [...], layout: {...} }'}</code>.
				</p>
			{/if}
		{:else if isPythonCell}
			<div class="notebook-code-block">
				<Editor
					bind:this={editorRef}
					code={cell.code}
					errors={cell.errors}
					language="python"
					pythonContext={{ kind: 'data', notebookId }}
					pythonSchemas={prevCellSources}
					{dark}
					layout={editorLayout}
					embeddedNotebook
					onchange={(c) => updatePythonCellCode(cell.id, c)}
				/>
			</div>
			{#if !worksheet}
				<p class="mt-1 text-2xs text-muted-foreground">
					Reference upstream cells by name — they're already DataFrames. End the cell with a bare
					expression (like Jupyter), or assign to <code>result</code> or
					<code>fig</code>, to surface a table or Plotly chart.
				</p>
			{/if}
		{:else if !isQueryCell}
			<div class="group/markdown relative" bind:this={markdownEditContainerEl}>
				{#if !worksheet && !reportView && !collapsed}
					<MarkdownModeBar
						mode={markdownMode}
						preview={isMarkdownOutputOnly}
						onModeChange={setMarkdownMode}
						onPreviewChange={setMarkdownPreviewMode}
					/>
				{/if}
				{#if isMarkdownOutputOnly}
					<!-- svelte-ignore a11y_no_static_element_interactions a11y_click_events_have_key_events -->
					<div
						class="markdown-body prose"
						class:cursor-text={!reportView}
						onclick={!reportView ? handleMarkdownPreviewClick : undefined}
					>
						{#if markdocResult}
							<MarkdocRenderer
								content={markdocResult.tree}
								errors={markdocResult.errors}
								{notebookId}
								headingSlugPrefix={cell.id}
							/>
						{/if}
					</div>
				{:else}
					<div class="markdown-editor-stack relative min-h-24">
						<div
							class="transition-opacity duration-(--motion-fast) {isMarkdownVisualEditing
								? 'pointer-events-auto relative opacity-100'
								: 'pointer-events-none absolute inset-0 opacity-0'}"
						>
							{#if TyporaEditor}
								<TyporaEditor
									value={cell.markdown ?? ''}
									onchange={(v) => updateCellMarkdown(cell.id, v)}
									cells={markdownValidationCells}
									{notebookId}
									refEntries={markdownRefEntries}
								/>
							{:else}
								<div class="min-h-28 rounded-sm bg-muted/15 p-3 text-xs text-muted-foreground">
									Loading visual editor…
								</div>
							{/if}
						</div>
						<div
							class="transition-opacity duration-(--motion-fast) {isMarkdownSourceEditing
								? 'pointer-events-auto relative opacity-100'
								: 'pointer-events-none absolute inset-0 opacity-0'}"
						>
							<MarkdownToolbar
								{refPickerEntries}
								onFormat={handleToolbarFormat}
								onInsertSnippet={insertMarkdownSnippet}
								onInsertRef={insertMarkdownRef}
							/>
							<MarkdownEditor
								bind:handle={markdownHandle}
								value={cell.markdown ?? ''}
								onchange={(v) => updateCellMarkdown(cell.id, v)}
								refEntries={markdownRefEntries}
								cellsForValidation={markdownValidationCells}
							/>
						</div>
					</div>
					{#if hasLiveRefs}
						<p class="mt-0.5 text-2xs text-muted-foreground select-none">
							⚡ Live refs active — run upstream cells to update values
						</p>
					{/if}
				{/if}
			</div>
		{:else if cell.editMode === 'gui'}
			<div class={worksheet ? 'min-h-0 flex-1 overflow-y-auto' : ''}>
				<GUIEditor
					stages={cell.guiStages}
					tables={guiTables}
					{prevCellSources}
					{dark}
					connectionId={connectionValue}
					{connectionType}
					stageResultsCollapsed={cell.stageResultsCollapsed}
					{stageErrorMap}
					onStagesChange={(stages) => updateGuiStages(cell.id, stages)}
					onRunStage={(upToStageIdx) => runGuiStagePreview(cell.id, upToStageIdx)}
					onStageResultCollapsedChange={(stageIdx, c) =>
						setStageResultCollapsed(cell.id, stageIdx, c)}
					onEscapeEditor={() => cellContainerEl?.focus()}
				/>
			</div>
		{:else}
			<div class="notebook-code-block">
				<Editor
					bind:this={editorRef}
					code={cell.code}
					errors={cell.errors}
					completions={editorCompletions}
					language={cell.language}
					sqlDialect={cellSqlDialect}
					{connectionType}
					connectionId={connectionValue}
					externalSchema={cellExternalSchema}
					{udfFunctionNames}
					{dark}
					layout={editorLayout}
					embeddedNotebook
					onchange={(c) => updateCellCode(cell.id, c)}
				/>
			</div>
		{/if}
	{/snippet}

	{#snippet outputInner()}
		<!-- Compiled SQL preview -->
		{#if sqlExpanded && cell.compiledSQL}
			<CellSqlPreview sql={cell.compiledSQL} />
		{/if}

		<!-- Errors — quiet inline annotation bar (plot cells show errors inline
					     in their own output area instead, via PlotCellOutput below) -->
		{#if !isPlotCell && cell.errors.length > 0}
			<div
				class="space-y-0.5 pl-0.5 {worksheet ? 'shrink-0' : ''}"
				in:fly={{ y: -4, duration: 130 }}
			>
				{#each cell.errors as error, errorIdx (errorIdx)}
					<div class="rounded-r-sm border-destructive/80 py-2">
						<p class="font-mono text-xs leading-snug whitespace-pre-wrap text-destructive/90">
							{error.display ?? error.reason}
						</p>
					</div>
				{/each}
			</div>
		{/if}

		{#if cell.materializeError}
			<div in:fly={{ y: -4, duration: 130 }} class="rounded-r-sm py-2">
				<p class="font-mono text-xs leading-snug whitespace-pre-wrap text-destructive/90">
					{cell.materializeError}
				</p>
			</div>
		{/if}

		<!-- Plot cell output: rendered reactively from cell.code + its
					     resolved upstream cells' .result, same as ChartView's plotRender
					     derived — not stored state, so it stays live as you type. -->
		{#if isPlotCell}
			<div in:fade={{ duration: 220 }} class={worksheet ? 'min-h-0 flex-1' : 'min-h-64'}>
				<PlotCellOutput {cell} deps={plotDeps} />
			</div>
		{/if}

		<!-- Python cell output: stdout + captured Plotly figures + traceback.
					     The resulting DataFrame (if any) renders below via the shared
					     Results block, same InlineResultView every other cell type uses. -->
		{#if showPythonOutput}
			<div in:fade={{ duration: 220 }} class={worksheet ? 'shrink-0' : ''}>
				<PythonCellOutput output={cell.pythonOutput!} />
			</div>
		{/if}

		<!-- Results -->
		{#if !cell.hideResult && cell.result && (cell.status === 'success' || cell.status === 'running')}
			<div
				in:fade={{ duration: 220 }}
				class="relative transition-opacity duration-(--motion-slow) {worksheet
					? 'flex min-h-0 flex-1 flex-col'
					: ''} {running ? 'opacity-70' : 'opacity-100'}"
			>
				{#if running}
					<div
						class="pointer-events-none absolute top-3 right-3 z-10 inline-flex items-center gap-1 rounded-full border border-border/70 bg-background/90 px-2 py-1 text-2xs font-medium text-muted-foreground shadow-sm backdrop-blur-[2px]"
					>
						<Loader2 class="h-3 w-3 animate-spin" />
						<span>Updating</span>
					</div>
				{/if}
				{#if cell.result.rows.length === 0}
					<p class="text-xs text-muted-foreground italic">Query returned 0 rows.</p>
				{:else}
					<div class="notebook-output-block">
						<InlineResultView
						rows={cell.result.rows}
						columns={cell.result.columns}
						truncated={cell.result.truncated ?? false}
						name={cell.outputName || `result${index + 1}`}
						initialViewMode={cell.resultViewMode}
						initialChartConfig={cell.resultChartConfig}
						controlsVisible={showResultControls}
						toolbarReserveSpace={!codeHidden}
						fillHeight={worksheet}
						onViewModeChange={(mode) => setCellResultViewMode(cell.id, mode)}
						onChartConfigChange={(config) => setCellResultChartConfig(cell.id, config)}
						onAddSort={cell.editMode === 'gui' ? addSortSuggestion : undefined}
						onAddFilter={cell.editMode === 'gui' ? addFilterSuggestion : undefined}
						columnFormatRules={cell.columnFormatRules}
						onColumnFormatRulesChange={(rules) => updateCellColumnFormatRules(cell.id, rules)}
						columnDescriptions={isDbtProject ? columnDescriptions : undefined}
						onColumnDescriptionChange={isDbtProject ? handleColumnDescriptionChange : undefined}
					>
						{#snippet toolbarActions()}
							{#if onOpenResultTab}
								<div
									class="flex items-center gap-1 transition-opacity duration-(--motion-fast) ease-(--motion-ease-out) {showResultControls
										? 'opacity-100'
										: 'pointer-events-none opacity-0'}"
									aria-hidden={!showResultControls}
								>
									<Tooltip.Root>
										<Tooltip.Trigger>
											<Button
												variant="ghost"
												size="sm"
												class="h-6 w-6 p-0"
												onclick={() =>
													onOpenResultTab!(
														cell.id,
														notebookId,
														cell.outputName || `result${index + 1}`,
														cell.resultViewMode
													)}><ExternalLink class="h-3 w-3" /></Button
											>
										</Tooltip.Trigger>
										<Tooltip.Content><p class="text-xs">Open in full tab</p></Tooltip.Content>
									</Tooltip.Root>
								</div>
							{/if}
						{/snippet}
					</InlineResultView>
					</div>
				{/if}
			</div>
		{/if}

		{#if hasStatusLine}
			<CellStatusLine
				{cell}
				{showResult}
				{running}
				{intelligenceSummary}
				connectionName={cellConnectionName}
				{isDbtProject}
				onOpenMaterialize={() => (materializeDialogOpen = true)}
				onShowSql={() => (sqlExpanded = true)}
				onRunTests={() => void testCell(cell.id)}
				onOverlayChange={handleOverlayChange}
				onOpenFull={onOpenResultTab && cell.result && cell.result.rows.length > 50
					? () =>
							onOpenResultTab!(
								cell.id,
								notebookId,
								cell.outputName || `result${index + 1}`,
								'table'
							)
					: undefined}
			/>
		{/if}
	{/snippet}

	{#snippet cellMain()}
		{#if !collapsed}
			{#if worksheet}
				<div class="flex min-h-0 flex-1 flex-col">
					<div
						style="height: {editorHeight}px"
						class="flex min-h-40 shrink-0 flex-col overflow-hidden"
					>
						{#if !codeHidden}
							<div onfocusin={onEditorFocus} class="flex min-h-0 flex-1 flex-col overflow-hidden">
								{@render editorInner()}
							</div>
						{/if}
					</div>
					<div
						class="group flex h-2 w-full shrink-0 cursor-ns-resize touch-none items-center justify-center select-none"
						role="separator"
						aria-label="Resize editor"
						onpointerdown={onSplitResizeStart}
						onpointermove={onSplitResizeMove}
						onpointerup={onSplitResizeEnd}
						onpointercancel={onSplitResizeEnd}
					>
						<div
							class="h-0.5 w-10 rounded-full bg-border/40 transition-colors group-hover:bg-border {splitResizing
								? 'bg-primary/50'
								: ''}"
						></div>
					</div>
					<div class="flex min-h-0 flex-1 flex-col gap-1 overflow-hidden">
						{@render outputInner()}
					</div>
				</div>
			{:else}
				<div class="flex flex-col gap-1" transition:slide={{ duration: 220 }}>
					{#if !codeHidden}
						<div onfocusin={onEditorFocus}>
							{@render editorInner()}
						</div>
					{/if}
					{@render outputInner()}
				</div>
			{/if}
		{/if}
	{/snippet}

	{#if worksheet}
		<div
			bind:this={worksheetBodyEl}
			data-worksheet="true"
			class="flex min-h-0 flex-1 flex-col overflow-hidden px-4 pb-3"
		>
			{#if !(reportView && !isQueryCell) && !(isMarkdownCell && isMarkdownPreviewMode)}
				<div class="shrink-0 pt-2 pb-1">
					<CellHeader
						{cell}
						{isQueryCell}
						{isMarkdownCell}
						collapsed={false}
						codeHidden={false}
						revealed={true}
						{reportView}
						hidden={false}
						{prevCellNames}
						downstreamCount={sameNotebookUsageCount}
						{crossNotebookUsageCount}
						{cellMode}
						onModeChange={setCellMode}
						onOverlayChange={handleOverlayChange}
						onFixWithAI={canInlinePrompt || onFixWithAI ? handleFixWithAI : undefined}
					/>
				</div>
			{/if}
			{@render cellMain()}
		</div>
	{:else}
		<div
			class="grid grid-cols-[var(--notebook-gutter-width)_minmax(0,1fr)] gap-x-2 overflow-visible"
		>
			{#if reportView}
				<div class="notebook-cell-gutter" aria-hidden="true"></div>
			{:else}
				<aside
					class="notebook-cell-gutter flex flex-col items-center gap-0.5 self-start pt-0.5"
					aria-label="Cell controls"
				>
					{#if isQueryCell || isPythonCell}
						<span
							class="pointer-events-none font-mono text-2xs leading-none font-medium text-muted-foreground/45 tabular-nums transition-opacity duration-(--motion-fast) {showCellIndex
								? 'opacity-100'
								: 'opacity-0'}"
							aria-hidden="true"
						>
							{index + 1}
						</span>
					{/if}
					<button
						type="button"
						class="flex h-5 w-5 cursor-grab items-center justify-center rounded text-muted-foreground/35 transition-[opacity,color,background-color] duration-(--motion-fast) outline-none hover:bg-muted/50 hover:text-muted-foreground active:cursor-grabbing {revealed
							? 'opacity-100'
							: 'pointer-events-none opacity-0'}"
						data-drag-handle
						tabindex="-1"
						aria-label="Drag to reorder cell"
						title="Drag to reorder"
					>
						<GripVertical class="h-3.5 w-3.5" />
					</button>
					<CellGutter
						isQueryCell={isQueryCell || isPythonCell || isPlotCell}
						{revealed}
						status={cell.status}
						needsRun={cell.needsRun}
						{running}
						runTooltip={runTooltipText}
						onRun={() =>
							isPythonCell
								? runPythonCell(cell.id)
								: isPlotCell
									? runPlotCell(cell.id)
									: runCell(cell.id)}
						onCancel={() => cancelCell(cell.id)}
						commentCount={collabEnabled ? commentCount : 0}
						onComments={collabEnabled && !reportView ? openCellComments : undefined}
					>
						{#snippet menu()}
							<CellMenu
								{cell}
								{notebookId}
								{isQueryCell}
								{isPythonCell}
								{isFirst}
								{isLast}
								{isDbtProject}
								{connections}
								{connectionValue}
								bind:sqlExpanded
								bind:open={menuOpen}
								onOpenMaterialize={() => (materializeDialogOpen = true)}
								onOpenPromote={() => (promoteDialogOpen = true)}
								onOpenPromoteSeed={() => (promoteSeedDialogOpen = true)}
								onRunTests={() => void testCell(cell.id)}
								onOpenInlinePrompt={canInlinePrompt ? () => (inlinePromptOpen = true) : undefined}
								onOpenWorksheet={supportsWorksheet ? handleOpenWorksheet : undefined}
								{onShareWithAI}
								{isPlotCell}
							/>
						{/snippet}
					</CellGutter>
				</aside>
			{/if}

			<div class="notebook-cell-body min-w-0 flex flex-col gap-1">
				{#if !(reportView && !isQueryCell) && !(isMarkdownCell && isMarkdownPreviewMode)}
					<CellHeader
						{cell}
						{isQueryCell}
						{isMarkdownCell}
						{collapsed}
						codeHidden={headerCodeHidden}
						{revealed}
						{reportView}
						hidden={isMarkdownPreviewMode}
						{prevCellNames}
						downstreamCount={sameNotebookUsageCount}
						{crossNotebookUsageCount}
						{cellMode}
						onModeChange={setCellMode}
						onOverlayChange={handleOverlayChange}
						onFixWithAI={canInlinePrompt || onFixWithAI ? handleFixWithAI : undefined}
					/>
				{/if}
				{@render cellMain()}
			</div>
		</div>
	{/if}

	{#if isQueryCell}
		<MaterializeDialog bind:open={materializeDialogOpen} {cell} {isDbtProject} />
		<PromoteDialog bind:open={promoteDialogOpen} {cell} />
		<PromoteSeedDialog bind:open={promoteSeedDialogOpen} {cell} />
	{/if}
	<CellModeSwitchDialogs
		bind:confirmSwitchToGui
		bind:confirmSwitchToSql
		bind:confirmSwitchToPrql
		bind:confirmSwitchToVisualMarkdown
		onSwitchToGui={doSwitchToGui}
		onSwitchToSql={doSwitchToSql}
		onSwitchToPrql={doSwitchToPrql}
		onSwitchToVisualMarkdown={doSwitchToVisualMarkdown}
	/>
</div>

<style>
	.markdown-body {
		font-size: 0.875rem;
		line-height: 1.7;
	}
	.markdown-body :global(h1) {
		font-size: 1.3rem;
		font-weight: 700;
		margin: 0 0 0.6rem;
		line-height: 1.3;
	}
	.markdown-body :global(h2) {
		font-size: 1.1rem;
		font-weight: 600;
		margin: 0.75rem 0 0.4rem;
		line-height: 1.35;
	}
	.markdown-body :global(h3),
	.markdown-body :global(h4),
	.markdown-body :global(h5),
	.markdown-body :global(h6) {
		font-size: 0.9rem;
		font-weight: 600;
		margin: 0.6rem 0 0.3rem;
	}
	.markdown-body :global(p) {
		margin: 0 0 0.5rem;
	}
	.markdown-body :global(*:last-child) {
		margin-bottom: 0;
	}
	.markdown-body :global(ul),
	.markdown-body :global(ol) {
		padding-left: 1.25rem;
		margin: 0 0 0.5rem;
	}
	.markdown-body :global(li) {
		margin-bottom: 0.125rem;
	}
	.markdown-body :global(pre) {
		background: color-mix(in oklch, currentColor 6%, transparent);
		border-radius: 0.3rem;
		padding: 0.5rem 0.75rem;
		margin: 0 0 0.5rem;
		white-space: pre-wrap;
		word-break: break-word;
		font-family: var(--font-mono, ui-monospace, SFMono-Regular, monospace);
	}
	.markdown-body :global(code) {
		font-family: var(--font-mono, ui-monospace, SFMono-Regular, monospace);
		font-size: 0.85em;
		background: color-mix(in oklch, var(--primary) 10%, transparent);
		border: 1px solid color-mix(in oklch, var(--primary) 15%, transparent);
		border-radius: 0.25rem;
		padding: 0.1em 0.35em;
		color: var(--primary);
	}
	.markdown-body :global(pre code) {
		background: none;
		padding: 0;
	}
	.markdown-body :global(blockquote) {
		border-left: 3px solid var(--primary);
		margin: 0 0 0.5rem;
		padding-left: 0.85rem;
		color: var(--muted-foreground);
	}
	.markdown-body :global(hr) {
		border: none;
		border-top: 1px solid color-mix(in oklch, currentColor 15%, transparent);
		margin: 0.75rem 0;
	}
	.markdown-body :global(a) {
		color: var(--primary);
		text-decoration: underline;
		text-underline-offset: 3px;
	}
	.markdown-body :global(a:hover) {
		opacity: 0.75;
	}
	.markdown-body :global(del) {
		opacity: 0.6;
	}
	.markdown-body :global(h1) {
		border-bottom: 1px solid color-mix(in oklch, currentColor 10%, transparent);
		padding-bottom: 0.3rem;
		margin-bottom: 0.75rem;
	}
	.markdown-body :global(img) {
		max-width: 100%;
		border-radius: 0.25rem;
	}
</style>
